#!/opt/Python-3.4.1/python
#print("Content-Type:text/html\n\n")

#Date Last Modified: 	02-04-2014
#Module: 				adminForm.py
#Object: 				application that allows authorized user to modify the database
#Return:				

# Copyright (c) 2015, Gulf of Mexico Coastal and Ocean Observing System
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of H-N-Data nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
import os
import sys
import cgi, cgitb
import nutrientsApp
import gcoos_footer

cgitb.enable()

#HEADER
print('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">')
print('<html xmlns="http://www.w3.org/1999/xhtml">')
print('		<head>')
print('    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">')
print('    		<title>GCOOS Water Quality and Nutrients</title>')
print('    		<link href="css/gcoos_03.css" rel="stylesheet" type="text/css">')
print('    		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">')
print('    		<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">')
print('			<script type="text/javascript">')
print('      		var _gaq = _gaq || [];')
print('      		_gaq.push([\'_setAccount\', \'UA-5033874-2\']);')
print('      		_gaq.push([\'_trackPageview\']);')
print('      		(function() {')
print('        			var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;')
print('        			ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';')
print('        			var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);')
print('      		})();')
print('    		</script>')
print('		</head>')

#BODY
print('		<body class="thrColFixHdr" ng-app="nutrientsApp">')
print('		<div id="container">')
print('			<div id="header">')
print('				<div align="right">')
print('             	   <img src="images/gcoos_header_wq_nutrients.png" width="1200" height="120" border="0" usemap="#MapGCOOS" />')
print('                		<map name="MapGCOOS">')
print('                  		<area shape="rect" coords="4,3,1048,32" href="http://www.ioos.noaa.gov/" target="_blank" alt="About IOOS" />')
print('                  	 	<area shape="rect" coords="1055,2,1085,31" href="http://gcoos.org" target="_blank" alt="GCOOS Home" />')
print('                      	<area shape="rect" coords="1090,1,1120,30" href="../index.php" target="_blank" alt="GCOOS Data Portal" />')
print('                  	 	<area shape="rect" coords="1127,0,1157,29" href="http://gcoos.org/products/" target="_blank" alt="GCOOS Products" />')
print('                  		<area shape="rect" coords="1161,2,1191,31" href="https://www.facebook.com/GCOOS" target="_blank" alt="GCOOS Facebook" />')
print('                		</map>')
print('				</div>')
print('      	<!-- end header --></div>')
print('			<div ng-controller="TitleCtrl" class="row">')
print('				<div class="col-sm-offset-10">')
print('					<h5>{{greetStr}}<a href="" data-toggle="modal" data-target="{{dataTargetModal}}">{{actionStr}}</a></h5>')
print('				</div>')
print('			</div>')
print('			<div ng-controller="LoginCtrl">')
print('				<div class="modal fade" id="loginModal" role="dialog">')
print('					<div class="modal-dialog">')
print('						<div class="modal-content">')
print('							<div class="modal-header">')
print('								<h4 class="modal-title">GCOOS Admin Login</h4>')
print('							</div>')
print('							<div class="modal-body">')
print('								<form class="form-horizontal" role="form">')
print('									<div class="form-group">')
print('										<label class="col-sm-2" for="user">Username:</label>')
print('										<div class="col-sm-10">')
print('											<input ng-model="userName" type="user" class="form-control" id="user">')
print('										</div>')
print('									</div>')
print('									<div class="form-group">')
print('										<label class="col-sm-2" for="paswd">Password:</label>')
print('										<div class="col-sm-10">')
print('											<input ng-model="passWord" type="password" class="form-control" id="paswd">')
print('										</div>')
print('									</div>')
print('								</form>')
print('							</div>')
print('							<div class="modal-footer">')
print('								<button ng-click="verifyCredentials()" type="button" class="btn btn-primary btn-lg" data-dismiss="modal">Submit</button>')
print('							</div>')
print('						</div>')
print('					</div>')
print('				</div>')
print('				<div class="modal fade" id="logoutModal" role="dialog">')
print('					<div class="modal-dialog modal-sm">')
print('						<div class="modal-content">')
print('							<div class="modal-header">')
print('								<h4 class="modal-title">GCOOS Admin Logout</h4>')
print('							</div>')
print('							<div class="modal-body">')
print('								<p>Logout?</p>')
print('							</div>')
print('							<div class="modal-footer">')
print('								<button ng-click="verifyCredentials()" type="button" class="btn btn-primary btn-lg" data-dismiss="modal">Logout</button>')
print('							</div>')
print('						</div>')
print('					</div>')
print('				</div>')
print('			</div>')
print('			<div ng-controller="FormCtrl">')
print(' 			<hr class="formBorder"/>')
print(' 			<h4>Organizations</h4>')
print('				<div>')
print('					<form id="nutrientsMainForm" class="form-horizontal" role="form">')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="shortname">Shortname:</label>')
print('							<div class="col-sm-6">')
print('								<input ng-model="o_shortNameTextInput" placeholder="Select from the dropdown list on the right" class="form-control" ng-disabled="o_shortNameTextInputActive">')
print('							</div>')
print('							<div class="col-sm-5">')
print('								<select ng-model="o_shortNameInput" ng-options="org.shortname for org in orgList" ng-change="populatePlatform(o_shortNameInput)" type="shortname" class="form-control" id="shortname">')
print('								</select>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="name">Name:</label>')
print('							<div class="col-sm-6">')
print('								<input ng-model="o_nameTextInput" placeholder="Select from the dropdown list on the right" class="form-control" ng-disabled="o_nameTextInputActive">')
print('							</div>')
print('							<div class="col-sm-5">')
print('								<select ng-model="o_nameInput" ng-options="org.name for org in orgList" ng-change="populatePlatform(o_nameInput)" type="name" class="form-control" id="name">')
print('								</select>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="contactName">Contact Name:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="o_contactNameInput" type="contactName" class="form-control" id="contactName" ng-disabled="o_contactNameInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="contactEmail">Contact Email:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="o_contactEmailInput" type="contactEmail" class="form-control" id="contactEmail" ng-disabled="o_contactEmailInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="orgUrl">URL:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="o_urlInput" type="orgUrl" class="form-control" id="orgUrl" ng-disabled="o_urlInputActive">')
print('							</div>')
print('						</div>')
print('					</form>')
print('					<div class="row">')
print('						<div class="btn-group btn-group-md col-sm-offset-1 col-sm-2">')
print('							<button ng-click="traverseList(\'org\', \'GoBackAll\')" type="button" class="btn btn-primary">|&lt</button>')
print('							<button ng-click="traverseList(\'org\', \'GoBack\')" type="button" class="btn btn-primary">&lt</button>')
print('							<button ng-click="traverseList(\'org\', \'GoForward\')" type="button" class="btn btn-primary">&gt</button>')
print('							<button ng-click="traverseList(\'org\', \'GoForwardAll\')" type="button" class="btn btn-primary">&gt|</button>')
print('						</div>')
print('						<div class="btn-group btn-group-md col-sm-3">')
print('							<button ng-click="setActiveButton(\'BrowseOrganization\')" type="button" class="btn btn-primary {{o_browseActive}}">Browse</button>')
print('							<button ng-click="setActiveButton(\'AddOrganization\')" type="button" class="btn btn-primary {{o_addActive}}">Add</button>')
print('							<button ng-click="setActiveButton(\'EditOrganization\')" type="button" class="btn btn-primary {{o_editActive}}">Edit</button>')
print('							<button ng-click="setActiveButton(\'DeleteOrganization\')" type="button" class="btn btn-primary {{o_deleteActive}}">Delete</button>')
print('						</div>')
print('						<div class="col-sm-1">')
print('							<button ng-click="submitForm(\'orgForm\')" type="button" class="btn btn-primary btn-md">Submit</button>')
print('						</div>')
print('					</div>')
print('				</div>')
print(' 			<hr class="formBorder"/>')
print('				<h4>{{platformTitle}}</h4>')
print('				<div>')
print('					<form class="form-horizontal" role="form">')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="platName">Name:</label>')
print('							<div class="col-sm-6">')
print('								<input ng-model="p_nameTextInput" placeholder="Select from the dropdown list on the right" class="form-control" ng-disabled="p_nameTextInputActive">')
print('							</div>')
print('							<div class="col-sm-5">')
print('								<select ng-model="p_nameInput" ng-options="plat.name for plat in selectedPlatList" ng-change="populateSensor(p_nameInput)" type="platName" class="form-control" id="platName">')
print('								</select>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="description">Description:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="p_descriptionInput" type="description" class="form-control" id="description" ng-disabled="p_descriptionInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="latitude">Latitude:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="p_latitudeInput" type="latitude" class="form-control" id="latitude" ng-disabled="p_latitudeInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="longitude">Longitude:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="p_longitudeInput" type="longitude" class="form-control" id="longitude" ng-disabled="p_longitudeInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="platUrl">URL:</label>')
print('							<div class="col-sm-9">')
print('								<input ng-model="p_urlInput" type="platUrl" class="form-control" id="platUrl" ng-disabled="p_urlInputActive">')
print('							</div>')
print('							<div class="col-sm-2">')
print('								<button type="button" class="btn btn-default" ng-click="openLink(\'URL\')">Test Link</button>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="rss">RSS:</label>')
print('							<div class="col-sm-9">')
print('								<input ng-model="p_rssInput" type="rss" class="form-control" id="rss" ng-disabled="p_rssInputActive">')
print('							</div>')
print('							<div class="col-sm-2">')
print('								<button type="button" class="btn btn-default" ng-click="openLink(\'RSS\')">Test Link</button>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="platImg">Image:</label>')
print('							<div class="col-sm-9">')
print('								<input ng-model="p_imageInput" type="platImg" class="form-control" id="platImg" ng-disabled="p_imageInputActive">')
print('							</div>')
print('							<div class="col-sm-2">')
print('								<button type="button" class="btn btn-default" ng-click="openLink(\'IMAGE\')">Test Link</button>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="urn">URN:</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="p_urnInput" type="urn" class="form-control" id="urn" placeholder="urn:ioos:stations:{organization}:{provider}:{station label}" ng-disabled="p_urnInputActive">')
print('							</div>')
print('						</div>')
print('					</form>')
print('					<div class="row">')
print('						<div class="btn-group btn-group-md col-sm-offset-1 col-sm-2">')
print('							<button ng-click="traverseList(\'plat\', \'GoBackAll\')" type="button" class="btn btn-primary">|&lt</button>')
print('							<button ng-click="traverseList(\'plat\', \'GoBack\')" type="button" class="btn btn-primary">&lt</button>')
print('							<button ng-click="traverseList(\'plat\', \'GoForward\')" type="button" class="btn btn-primary">&gt</button>')
print('							<button ng-click="traverseList(\'plat\', \'GoForwardAll\')" type="button" class="btn btn-primary">&gt|</button>')
print('						</div>')
print('						<div class="btn-group btn-group-md col-sm-3">')
print('							<button ng-click="setActiveButton(\'BrowsePlatform\')" type="button" class="btn btn-primary {{p_browseActive}}">Browse</button>')
print('							<button ng-click="setActiveButton(\'AddPlatform\')" type="button" class="btn btn-primary {{p_addActive}}">Add</button>')
print('							<button ng-click="setActiveButton(\'EditPlatform\')" type="button" class="btn btn-primary {{p_editActive}}">Edit</button>')
print('							<button ng-click="setActiveButton(\'DeletePlatform\')" type="button" class="btn btn-primary {{p_deleteActive}}">Delete</button>')
print('						</div>')
print('						<div class="col-sm-1">')
print('							<button ng-click="submitForm(\'platForm\')" type="button" class="btn btn-primary btn-md">Submit</button>')
print('						</div>')
print('					</div>')
print('				</div>')
print(' 			<hr class="formBorder"/>')
print('				<h4>{{sensorTitle}}</h4>')
print('				<div>')
print('					<form class="form-horizontal" role="form">')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="sensorType">Sensor Type</label>')
print('							<div class="col-sm-11">')
print('								<select ng-model="s_sensorTypeInput" ng-options="sens.shortTypeName for sens in sensTypeList" ng-change="" type="sensorType" class="form-control" id="sensorType" ng-disabled="s_sensorTypeInputActive">')
print('								</select>')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="verticalPosition">Vertical Position</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="s_verticalPositionInput" type="verticalPosition" class="form-control" id="verticalPosition" ng-disabled="s_verticalPositionInputActive">')
print('							</div>')
print('						</div>')
print('						<div class="form-group">')
print('							<label style="font-weight: normal;" class="col-sm-1" for="sensorNumber">Sensor Number</label>')
print('							<div class="col-sm-11">')
print('								<input ng-model="s_numberInput" type="sensorNumber" class="form-control" id="sensorNumber" ng-disabled="s_numberInputActive">')
print('							</div>')
print('						</div>')
print('					</form>')
print('					<div class="row">')
print('						<div class="btn-group btn-group-md col-sm-offset-1 col-sm-2">')
print('							<button ng-click="traverseList(\'sens\', \'GoBackAll\')" type="button" class="btn btn-primary">|&lt</button>')
print('							<button ng-click="traverseList(\'sens\', \'GoBack\')" type="button" class="btn btn-primary">&lt</button>')
print('							<button ng-click="traverseList(\'sens\', \'GoForward\')" type="button" class="btn btn-primary">&gt</button>')
print('							<button ng-click="traverseList(\'sens\', \'GoForwardAll\')" type="button" class="btn btn-primary">&gt|</button>')
print('						</div>')
print('						<div class="btn-group btn-group-md col-sm-3">')
print('							<button ng-click="setActiveButton(\'BrowseSensor\')" type="button" class="btn btn-primary {{s_browseActive}}">Browse</button>')
print('							<button ng-click="setActiveButton(\'AddSensor\')" type="button" class="btn btn-primary {{s_addActive}}">Add</button>')
print('							<button ng-click="setActiveButton(\'EditSensor\')" type="button" class="btn btn-primary {{s_editActive}}">Edit</button>')
print('							<button ng-click="setActiveButton(\'DeleteSensor\')" type="button" class="btn btn-primary {{s_deleteActive}}">Delete</button>')
print('						</div>')
print('						<div class="col-sm-1">')
print('							<button ng-click="submitForm(\'sensForm\')" type="button" class="btn btn-primary btn-md">Submit</button>')
print('						</div>')
print('					</div>')
print('				</div>')
print('				<hr class="formBorder"/>')
print('			</div>')
print('		<!-- end #container --> </div>')
print('		<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>')
print('		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>')
print('		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-route.min.js"></script>')
print('		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>')
nutrientsApp.nutrientsApp()
print('</body>')
print('</html>')